<?php
/**
 * PeakURL runtime configuration template.
 *
 * This file is the sample `config.php` shipped with every release
 * package.  The browser-based installer (`setup-config.php`) reads
 * this template, replaces the `{{PLACEHOLDER}}` tokens with real
 * values, and writes the result as the root `config.php`.
 *
 * Do NOT edit this file directly on a live install—modify `config.php`
 * instead.
 *
 * @package PeakURL\Site
 * @since 1.0.0
 */

if ( ! defined( 'PEAKURL_ENV' ) ) {
	define( 'PEAKURL_ENV', {{PEAKURL_ENV}} );
}

if ( ! defined( 'PEAKURL_DEBUG' ) ) {
	define( 'PEAKURL_DEBUG', {{PEAKURL_DEBUG}} );
}

if ( ! defined( 'SITE_URL' ) ) {
	define( 'SITE_URL', {{SITE_URL}} );
}

if ( ! defined( 'PEAKURL_UPDATE_MANIFEST_URL' ) ) {
	define( 'PEAKURL_UPDATE_MANIFEST_URL', {{PEAKURL_UPDATE_MANIFEST_URL}} );
}

if ( ! defined( 'PEAKURL_CONTENT_DIR' ) ) {
	define( 'PEAKURL_CONTENT_DIR', {{PEAKURL_CONTENT_DIR}} );
}

if ( ! defined( 'PEAKURL_GEOIP_DB_PATH' ) ) {
	define( 'PEAKURL_GEOIP_DB_PATH', {{PEAKURL_GEOIP_DB_PATH}} );
}

if ( ! defined( 'PEAKURL_MAXMIND_ACCOUNT_ID' ) ) {
	define( 'PEAKURL_MAXMIND_ACCOUNT_ID', {{PEAKURL_MAXMIND_ACCOUNT_ID}} );
}

if ( ! defined( 'PEAKURL_MAXMIND_LICENSE_KEY' ) ) {
	define( 'PEAKURL_MAXMIND_LICENSE_KEY', {{PEAKURL_MAXMIND_LICENSE_KEY}} );
}

if ( ! defined( 'PEAKURL_MAIL_DRIVER' ) ) {
	define( 'PEAKURL_MAIL_DRIVER', {{PEAKURL_MAIL_DRIVER}} );
}

if ( ! defined( 'PEAKURL_SMTP_HOST' ) ) {
	define( 'PEAKURL_SMTP_HOST', {{PEAKURL_SMTP_HOST}} );
}

if ( ! defined( 'PEAKURL_SMTP_PORT' ) ) {
	define( 'PEAKURL_SMTP_PORT', {{PEAKURL_SMTP_PORT}} );
}

if ( ! defined( 'PEAKURL_SMTP_ENCRYPTION' ) ) {
	define( 'PEAKURL_SMTP_ENCRYPTION', {{PEAKURL_SMTP_ENCRYPTION}} );
}

if ( ! defined( 'PEAKURL_SMTP_AUTH' ) ) {
	define( 'PEAKURL_SMTP_AUTH', {{PEAKURL_SMTP_AUTH}} );
}

if ( ! defined( 'PEAKURL_SMTP_USERNAME' ) ) {
	define( 'PEAKURL_SMTP_USERNAME', {{PEAKURL_SMTP_USERNAME}} );
}

if ( ! defined( 'PEAKURL_SMTP_PASSWORD' ) ) {
	define( 'PEAKURL_SMTP_PASSWORD', {{PEAKURL_SMTP_PASSWORD}} );
}

if ( ! defined( 'DB_HOST' ) ) {
	define( 'DB_HOST', {{DB_HOST}} );
}

if ( ! defined( 'DB_PORT' ) ) {
	define( 'DB_PORT', {{DB_PORT}} );
}

if ( ! defined( 'DB_DATABASE' ) ) {
	define( 'DB_DATABASE', {{DB_DATABASE}} );
}

if ( ! defined( 'DB_USERNAME' ) ) {
	define( 'DB_USERNAME', {{DB_USERNAME}} );
}

if ( ! defined( 'DB_PASSWORD' ) ) {
	define( 'DB_PASSWORD', {{DB_PASSWORD}} );
}

if ( ! defined( 'DB_CHARSET' ) ) {
	define( 'DB_CHARSET', {{DB_CHARSET}} );
}

$table_prefix = {{DB_PREFIX}};

if ( ! defined( 'SESSION_COOKIE_NAME' ) ) {
	define( 'SESSION_COOKIE_NAME', {{SESSION_COOKIE_NAME}} );
}

if ( ! defined( 'SESSION_LIFETIME' ) ) {
	define( 'SESSION_LIFETIME', {{SESSION_LIFETIME}} );
}

if ( ! defined( 'SESSION_COOKIE_PATH' ) ) {
	define( 'SESSION_COOKIE_PATH', {{SESSION_COOKIE_PATH}} );
}

if ( ! defined( 'SESSION_COOKIE_DOMAIN' ) ) {
	define( 'SESSION_COOKIE_DOMAIN', {{SESSION_COOKIE_DOMAIN}} );
}

if ( ! defined( 'SESSION_COOKIE_SAME_SITE' ) ) {
	define( 'SESSION_COOKIE_SAME_SITE', {{SESSION_COOKIE_SAME_SITE}} );
}

if ( ! defined( 'SESSION_COOKIE_SECURE' ) ) {
	define( 'SESSION_COOKIE_SECURE', {{SESSION_COOKIE_SECURE}} );
}
