import type { MouseEventHandler, ReactNode, WheelEventHandler } from "react";
import { Mercator } from "@visx/geo";
import type { GeoPermissibleObjects } from "@visx/geo";
import { cn } from "@/utils";
import type { GeographyFeature } from "../../types";

/**
 * Normalized map feature produced by the Mercator projection renderer.
 */
export interface RenderedMapFeature {
	/** Source geography feature from the world atlas payload. */
	feature: GeographyFeature;

	/** SVG path generated by the projection. */
	path: string | null;
}

interface WorldMapCanvasProps {
	/** Fixed SVG viewBox width used by the projection. */
	width: number;

	/** Fixed SVG viewBox height used by the projection. */
	height: number;

	/** Loaded world atlas geographies. */
	geographies: GeoPermissibleObjects[];

	/** Horizontal map offsets rendered for wrapped panning. */
	mapCopyOffsets: number[];

	/** Current Zoom transform rendered as an SVG transform string. */
	transform: string;

	/** Whether the map is currently being dragged. */
	isDragging: boolean;

	/** Start dragging the map. */
	onDragStart: MouseEventHandler<SVGSVGElement>;

	/** Continue dragging the map. */
	onDragMove: MouseEventHandler<SVGSVGElement>;

	/** End dragging the map. */
	onDragEnd: MouseEventHandler<SVGSVGElement>;

	/** Handle wheel zoom gestures. */
	onWheel: WheelEventHandler<SVGSVGElement>;

	/** Handle pointer exit from the map canvas. */
	onMouseLeave: () => void;

	/** Render one projected country path. */
	renderCountryPath: (
		feature: RenderedMapFeature,
		index: number,
		isDragging: boolean
	) => ReactNode;
}

/**
 * Render the interactive SVG map surface.
 */
const WorldMapCanvas = ({
	width,
	height,
	geographies,
	mapCopyOffsets,
	transform,
	isDragging,
	onDragStart,
	onDragMove,
	onDragEnd,
	onWheel,
	onMouseLeave,
	renderCountryPath,
}: WorldMapCanvasProps) => (
	<svg
		viewBox={`0 0 ${width} ${height}`}
		className={cn("world-map-svg", isDragging && "world-map-svg-dragging")}
		onMouseDown={onDragStart}
		onMouseMove={onDragMove}
		onMouseUp={onDragEnd}
		onWheel={onWheel}
		onMouseLeave={onMouseLeave}
	>
		<rect width={width} height={height} fill="transparent" />
		<g transform={transform}>
			{geographies.length > 0 && (
				<Mercator
					data={geographies}
					scale={147}
					translate={[width / 2, height / 2]}
					center={[0, 20]}
				>
					{({ features }) =>
						mapCopyOffsets.map((mapOffset) => (
							<g
								key={`world-copy-${mapOffset}`}
								transform={`translate(${mapOffset} 0)`}
							>
								{(features as RenderedMapFeature[]).map(
									(feature, index) =>
										renderCountryPath(
											feature,
											index,
											isDragging
										)
								)}
							</g>
						))
					}
				</Mercator>
			)}
		</g>
	</svg>
);

export default WorldMapCanvas;
